CREATE TABLE IF NOT EXISTS stories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  user_name VARCHAR(150) NOT NULL,
  text VARCHAR(255) NOT NULL,
  bg VARCHAR(20) DEFAULT '#1d4ed8',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
